package:
  name: precovery
  version: "{{ version }}"

source:
  git_url: "https://github.com/B612-Asteroid-Institute/precovery.git"
  git_tag: "v{{ version }}"

requirements:
  host:
    - python {{ python }}
    - pip
    - setuptools >=45
    - setuptools_scm >=6.0
    - wheel
  run:
    - python {{ python }}
    - numpy
    - numba
    - sqlalchemy
    - regex
    - pandas
    - healpy
    - requests
    - openorb
  test:
    - flake8
    - black
    - isort
    - mypy
    - pytest
    - pytest-cov

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt

test:
  imports:
    - precovery

about:
  home: https://github.com/B612-Asteroid-Institute/precovery
  license: BSD-3 Clause
  license_file: LICENSE.md
