name: Lint and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2
      - uses: jpribyl/action-docker-layer-caching@v0.1.0
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
      - name: Build Precovery in Docker
        run: docker build --load -t precovery:$IMAGE_TAG .
      - name: lint
        run: docker run -i precovery:$IMAGE_TAG pre-commit run --all-files
      - name: lint tests
        run: docker run -i precovery:$IMAGE_TAG pytest --log-level=INFO --log-cli-level=INFO -vv --exitfirst .
