name: Lint and Test

on:
  push:
    branches: [ main, "v*"]
  pull_request:
    branches: [ main, "v*"]

jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    env:
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3
      - name: Get git tags
        run:  git fetch --prune --unshallow --tags

      # Use pip to install dependencies
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: true
          cache-dependency-path: ./pyproject.toml
      - name: Install dependencies
        run: |
          pdm install -G test
      - name: Run linter
        run: |
          pdm run check
      # Run tests
      - name: Run tests
        run: |
          pdm run coverage
      - name: Coveralls
        uses: coverallsapp/github-action@v2.0.0
        with:
          path-to-lcov: coverage.xml

      # Run benchmarks
      - name: Run benchmarks
        run: |
          pdm run benchmark --benchmark-json bench.json

      # If on main branch, upload benchmark results
      - name: Store main benchmark result
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v3
        with:
          name: main-benchmark
          path: bench.json
          retention-days: 30

      # If PR, download main benchmark data
      - name: Download main benchmark data
        if: github.event_name == 'pull_request'
        id: download-main-benchmark
        uses: actions/download-artifact@v3
        with:
          name: main-benchmark
          path: main-bench
        continue-on-error: true
          
      - name: Compare benchmarks
        if: github.event_name == 'pull_request' && steps.download-main-benchmark.outcome == 'success'
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Python Benchmark
          tool: 'pytest'
          output-file-path: bench.json
          external-data-json-path: main-bench/bench.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-always: true
          fail-threshold: '150%'
          auto-push: false
